import speech_recognition as sr

class JarvisListener:
    def __init__(self):
            self.recognizer = sr.Recognizer()
                    self.microphone = sr.Microphone()
                            
                                    # Adjusting these settings makes J.A.V.E.I.R.S. more "robust"
                                            self.recognizer.pause_threshold = 0.8  # Seconds of silence before a phrase is considered complete
                                                    self.recognizer.dynamic_energy_threshold = True

                                                        def listen(self):
                                                                """Listens for a command and returns it as text."""
                                                                        with self.microphone as source:
                                                                                    print("\n[J.A.V.E.I.R.S. is Listening...]")
                                                                                                
                                                                                                            # This helps filter out the fan or AC noise in your room
                                                                                                                        self.recognizer.adjust_for_ambient_noise(source, duration=0.5)
                                                                                                                                    
                                                                                                                                                try:
                                                                                                                                                                # Capture the audio
                                                                                                                                                                                audio = self.recognizer.listen(source, timeout=5, phrase_time_limit=10)
                                                                                                                                                                                                
                                                                                                                                                                                                                print("[Processing Voice...]")
                                                                                                                                                                                                                                # Convert audio to text using Google's engine
                                                                                                                                                                                                                                                query = self.recognizer.recognize_google(audio, language='en-in')
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                print(f"User said: {query}")
                                                                                                                                                                                                                                                                                                return query.lower()

                                                                                                                                                                                                                                                                                                            except sr.WaitTimeoutError:
                                                                                                                                                                                                                                                                                                                            # This happens if you don't say anything for 5 seconds
                                                                                                                                                                                                                                                                                                                                            return "none"
                                                                                                                                                                                                                                                                                                                                                        except sr.UnknownValueError:
                                                                                                                                                                                                                                                                                                                                                                        # This happens if it hears noise but can't understand words
                                                                                                                                                                                                                                                                                                                                                                                        print("[System Error: Could not understand audio]")
                                                                                                                                                                                                                                                                                                                                                                                                        return "none"
                                                                                                                                                                                                                                                                                                                                                                                                                    except sr.RequestError:
                                                                                                                                                                                                                                                                                                                                                                                                                                    print("[System Error: Speech Service Down]")
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return "none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Unexpected Error: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return "none"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # --- Test Script ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    listener = JarvisListener()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Testing J.A.V.E.I.R.S. Hearing...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            command = listener.listen()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if command != "none":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Test Successful. Command received: {command}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Test Failed. No clear command detected.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    